table CARRECORD dropped.
table LETTERS dropped.
table CLERICALOFFICER dropped.
table CRITICALITY dropped.
table TESTPART dropped.
table MECHANIC dropped.
table TEST dropped.
table TESTCENTRE dropped.
table SUPERVISOR dropped.
table CAR dropped.
table OWNER dropped.
table CAR created.
table CAR altered.
table CARRECORD created.
table CARRECORD altered.
table CLERICALOFFICER created.
table CLERICALOFFICER altered.
table MECHANIC created.
table MECHANIC altered.
table OWNER created.
table OWNER altered.
table LETTERS created.
table LETTERS altered.
table SUPERVISOR created.
table SUPERVISOR altered.
table TEST created.
table TEST altered.
table TESTCENTRE created.
table TESTCENTRE altered.
table TESTPART created.
table TESTPART altered.
table CRITICALITY created.
table CRITICALITY altered.
table CAR altered.
table CARRECORD altered.
table CLERICALOFFICER altered.
table MECHANIC altered.
table LETTERS altered.
table LETTERS altered.
table TEST altered.
table TEST altered.
table TESTCENTRE altered.
table TESTPART altered.
table TESTPART altered.
table CRITICALITY altered.
